# Generated by Django 4.2.25 on 2025-12-12 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collectables', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectable',
            name='type',
        ),
    ]
