# Generated by Django 4.2.25 on 2026-01-12 16:41

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectables', '0002_remove_collectable_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectable',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='collectable',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='collectable',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
