# Generated by Django 4.2.25 on 2026-01-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectables', '0003_alter_collectable_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectable',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
