# Generated by Django 4.2.25 on 2025-11-26 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morphgun', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weapon',
            options={'ordering': ['order'], 'verbose_name': 'Weapon', 'verbose_name_plural': 'Weapons'},
        ),
        migrations.AddField(
            model_name='weapon',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
