# Generated by Django 4.2.25 on 2025-11-27 06:33

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morphgun', '0002_alter_weapon_options_weapon_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='colour',
            name='description',
            field=models.TextField(default='No description yet.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colour',
            name='image',
            field=cloudinary.models.CloudinaryField(default='v1763855318/1e67e5cbe56466efefdbe523de1f023b0a0dc544_hq_grmzpj.jpg', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='image',
            field=cloudinary.models.CloudinaryField(default='v1763855318/1e67e5cbe56466efefdbe523de1f023b0a0dc544_hq_grmzpj.jpg', max_length=255, verbose_name='image'),
        ),
    ]
