# Generated by Django 4.2.25 on 2025-12-16 19:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('morphgun', '0003_colour_description_colour_image_alter_weapon_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeaponRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='morphgun.weapon')),
            ],
            options={
                'unique_together': {('user', 'weapon')},
            },
        ),
    ]
