# Generated by Django 4.2.25 on 2025-12-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morphgun', '0004_weaponrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='MorphGunUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('game', models.CharField(choices=[('jak2', 'Jak II'), ('jak3', 'Jak 3')], max_length=4)),
                ('effect', models.TextField()),
                ('requirement', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField(blank=True, help_text='Jak 3 only (Precursor Orbs)', null=True)),
                ('weapons', models.ManyToManyField(blank=True, related_name='upgrades', to='morphgun.weapon')),
            ],
            options={
                'ordering': ['game', 'name'],
            },
        ),
    ]
