# Generated by Django 4.2.25 on 2025-12-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morphgun', '0005_morphgunupgrade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colour',
            options={'ordering': ['order'], 'verbose_name': 'Colour', 'verbose_name_plural': 'Colours'},
        ),
        migrations.AddField(
            model_name='colour',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
