# Generated by Django 4.2.25 on 2026-01-12 16:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morphgun', '0006_alter_colour_options_colour_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colour',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
