# Generated by Django 4.2.25 on 2026-01-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morphgun', '0007_alter_colour_image_alter_weapon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morphgunupgrade',
            name='game',
            field=models.CharField(choices=[('jak2', 'Jak II'), ('jak3', 'Jak 3')], max_length=20),
        ),
    ]
