# Generated by Django 4.2.25 on 2026-01-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morphgun', '0008_alter_morphgunupgrade_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morphgunupgrade',
            name='game',
            field=models.CharField(choices=[('jak2', 'Jak II'), ('jak3', 'Jak 3')], max_length=25),
        ),
    ]
