# Generated by Django 4.2.25 on 2026-01-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morphgun', '0009_alter_morphgunupgrade_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='colour',
            name='hex_code',
            field=models.CharField(default='#ffffff', help_text='Hex colour code, e.g. #ff0000', max_length=7),
        ),
        migrations.AlterField(
            model_name='colour',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
