# Generated by Django 4.2.25 on 2025-12-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='character',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
