# Generated by Django 4.2.25 on 2026-01-12 16:41

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_alter_character_options_character_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='age',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='appearance',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='character',
            name='eyes',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='hair',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='height',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='occupation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='personality',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='character',
            name='quote',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='character',
            name='sex',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='skin',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='weight',
            field=models.CharField(max_length=50),
        ),
    ]
