# Generated by Django 4.2.25 on 2026-01-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_alter_character_age_alter_character_appearance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='age',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='eyes',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='hair',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='height',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='occupation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='skin',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='weight',
            field=models.CharField(max_length=50),
        ),
    ]
