# Generated by Django 4.2.25 on 2026-01-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_alter_character_age_alter_character_eyes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='sex',
            field=models.CharField(max_length=50),
        ),
    ]
