# Generated by Django 4.2.25 on 2025-11-26 00:59

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('hero_title', models.CharField(default='Adventure Awaits in Haven City', max_length=200)),
                ('hero_text', models.TextField(default='Explore Morph Gun mods, Characters, Collectibles and more!')),
            ],
        ),
    ]
